# This is a basic workflow to help you get started with Actions
 
name: GithubWorkflow
 
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: 
  #     - "main"
  # pull_request:
  #   branches: 
  #     - "main"
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: "Build"
        run: echo "Build"
 
  Test:
    needs: Build  # "Test" depends on the successful completion of the "Build" job
    runs-on: ubuntu-latest
    steps:
      - name: "Test Step of the workflow/pipeline"
        run: echo "Test Step"
 
  Prod:
    needs: Test  # Ensure that "Test" job runs before this job
    runs-on: ubuntu-latest  # Type of machine to run the job on
    name: 'ServiceNow DevOps Change'
    steps:
      - name: "Test Step of the workflow/pipeline"
        run: echo "Test Step"
